global:
  scrape_interval: 5s
  evaluation_interval: 10s

rule_files:
  - rules/alert_rules.yml

scrape_configs:
  - job_name: "telegraf"
    static_configs:
      - targets: ["telegraf:9273"]

  - job_name: "exporter"
    scrape_interval: 2s
    static_configs:
      - targets: ["exporter:8001"]

  - job_name: "cadvisor"
    static_configs:
    - targets: ["cadvisor:8080"]
    metrics_path: '/metrics'

alerting:
  alertmanagers:
    - static_configs:
        - targets: 
          - alertmanager:9093

