{
 "title": "SIRP Home New",
 "description": "Home Dashboard",
 "tags": [
  "System",
  "SIRP"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Security Incident Response Platform\n[System Resources](https://commonmark.org/help/)"
   }
  },
  {
   "title": "Container Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "rate(container_network_receive_packets_total{name!=\"\", interface=\"eth0\"}[1m])",
     "legendFormat": "{{name}}:Recv"
    },
    {
     "expr": "rate(container_network_receive_packets_total{name!=\"\", interface=\"eth0\"}[1m])",
     "legendFormat": "{{name}}:Transmit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mem_used_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Core",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_system{cpu!=\"cpu-total\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Container Resources  Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\"}/1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{name!=\"\"}[1m])*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_rss{name!=\"\"}/1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "rate(diskio_merged_reads{name!=\"loop0\"}[1m])",
     "legendFormat": "{{name}}-read"
    },
    {
     "expr": "rate(diskio_merged_writes{name!=\"loop0\"}[1m])",
     "legendFormat": "{{name}}-write"
    }
   ]
  },
  {
   "title": "MySql Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_bytes_sent[1m]) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySql Recv",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_bytes_received[1m]) / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}